// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abovfdrkeywcqaftozpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib3ZmZHJrZXl3Y3FhZnRvenByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NDY1MjYsImV4cCI6MjA3NjMyMjUyNn0.9MWGKGklf9XVehXLhsF8LWum2mAXBi_s85kpv4dPDNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe storage implementation that handles localStorage errors gracefully
const safeStorage = {
  getItem: (key: string) => {
    try {
      return localStorage?.getItem(key) ?? null;
    } catch (error) {
      console.warn('localStorage access denied:', error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage?.setItem(key, value);
    } catch (error) {
      console.warn('localStorage write failed:', error);
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage?.removeItem(key);
    } catch (error) {
      console.warn('localStorage remove failed:', error);
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});
